swagger: "2.0"
info:
  title: REST api for simple route app
  version: ""
host: /
consumes:
  - application/json
  - application/xml
  - application/gob
produces:
  - application/json
  - application/xml
  - application/gob
paths:
  /api/admin/driver:
    post:
      tags:
        - admin_service
      summary: add_manager admin_service
      description: |-
        admins could add drivers from main system

        **Required security scopes for jwt**:
          * `admin`
      operationId: admin_service#add_manager
      parameters:
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: false
          type: string
        - name: add_manager_request_body
          in: body
          required: true
          schema:
            $ref: '#/definitions/AdminServiceAddManagerRequestBody'
            required:
              - login
              - password
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "403":
          description: Forbidden response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/admin/driver/{manager_id}:
    delete:
      tags:
        - admin_service
      summary: drop_manager admin_service
      description: |-
        admins could delete managers from main system

        **Required security scopes for jwt**:
          * `admin`
      operationId: admin_service#drop_manager
      parameters:
        - name: manager_id
          in: path
          description: id менеджера, которого необходимо удалить
          required: true
          type: string
          format: uuid
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: false
          type: string
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "403":
          description: Forbidden response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/profile:
    get:
      tags:
        - auth_service
      summary: profile auth_service
      description: get user profile
      operationId: auth_service#profile
      parameters:
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/signin:
    post:
      tags:
        - auth_service
      summary: signin auth_service
      description: Creates a valid JWT
      operationId: auth_service#signin
      parameters:
        - name: Authorization
          in: header
          description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
          required: true
          type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/AuthServiceSigninResponseBody'
            required:
              - jwt
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - basic_header_Authorization: []
  /api/tasks/:
    get:
      tags:
        - tasks_service
      summary: list tasks tasks_service
      description: получить все задачи для текущего пользователя
      operationId: tasks_service#list tasks
      parameters:
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/tasks/{task_id}/:
    get:
      tags:
        - tasks_service
      summary: get task tasks_service
      description: получить задачу по id
      operationId: tasks_service#get task
      parameters:
        - name: task_id
          in: path
          description: id задачи
          required: true
          type: string
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/TasksServiceGetTaskOKResponseBody'
            required:
              - id
              - text_template
              - image
              - status
              - title
              - bots_num
              - proxies_num
              - targets_num
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/tasks/{task_id}/assign:
    post:
      tags:
        - tasks_service
      summary: assign proxies tasks_service
      description: присвоить ботам прокси
      operationId: tasks_service#assign proxies
      parameters:
        - name: task_id
          in: path
          description: id задачи
          required: true
          type: string
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
      responses:
        "200":
          description: OK response.
          schema:
            type: integer
            format: int64
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/tasks/{task_id}/force:
    delete:
      tags:
        - tasks_service
      summary: force delete tasks_service
      description: удалить задачу и все связанные с ней сущности. Использовать только для тестов
      operationId: tasks_service#force delete
      parameters:
        - name: task_id
          in: path
          description: id задачи
          required: true
          type: string
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/tasks/{task_id}/start:
    post:
      tags:
        - tasks_service
      summary: start task tasks_service
      description: 'начать выполнение задачи '
      operationId: tasks_service#start task
      parameters:
        - name: task_id
          in: path
          description: id задачи
          required: true
          type: string
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/tasks/{task_id}/stop:
    post:
      tags:
        - tasks_service
      summary: stop task tasks_service
      description: 'остановить выполнение задачи '
      operationId: tasks_service#stop task
      parameters:
        - name: task_id
          in: path
          description: id задачи
          required: true
          type: string
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
      responses:
        "200":
          description: OK response.
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/tasks/{task_id}/upload:
    post:
      tags:
        - tasks_service
      summary: upload files tasks_service
      description: загрузить файл с пользователями, прокси
      operationId: tasks_service#upload files
      consumes:
        - multipart/form-data
      parameters:
        - name: task_id
          in: path
          description: id задачи, в которую загружаем пользователей/прокси
          required: true
          type: string
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
        - name: Upload FilesRequestBody
          in: formData
          required: true
          schema:
            $ref: '#/definitions/TasksServiceUploadFilesRequestBody'
            required:
              - bots
              - proxies
              - targets
              - filenames
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/UploadErrorResponse'
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
  /api/tasks/draft:
    post:
      tags:
        - tasks_service
      summary: create task draft tasks_service
      description: создать драфт задачи
      operationId: tasks_service#create task draft
      parameters:
        - name: Authorization
          in: header
          description: JWT used for authentication
          required: true
          type: string
        - name: Create Task DraftRequestBody
          in: body
          required: true
          schema:
            $ref: '#/definitions/TasksServiceCreateTaskDraftRequestBody'
            required:
              - title
              - text_template
              - post_image
      responses:
        "200":
          description: OK response.
          schema:
            type: string
            format: uuid
        "400":
          description: Bad Request response.
          schema:
            type: string
        "401":
          description: Unauthorized response.
          schema:
            type: string
        "404":
          description: Not Found response.
          schema:
            type: string
        "500":
          description: Internal Server Error response.
          schema:
            type: string
      schemes:
        - http
      security:
        - jwt_header_Authorization: []
definitions:
  AdminServiceAddManagerRequestBody:
    title: AdminServiceAddManagerRequestBody
    type: object
    properties:
      login:
        type: string
        example: Corrupti quidem et facilis.
      password:
        type: string
        example: y7a
        minLength: 4
    example:
      login: Eligendi totam facilis quaerat voluptatem et dolore.
      password: 23n
    required:
      - login
      - password
  AuthServiceSigninResponseBody:
    title: AuthServiceSigninResponseBody
    type: object
    properties:
      jwt:
        type: string
        description: JWT token
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
    example:
      jwt: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
    required:
      - jwt
  BotAccountRecordRequestBody:
    title: BotAccountRecordRequestBody
    type: object
    properties:
      line_number:
        type: integer
        description: номер строки в исходном файле
        example: 1040135973139267313
        format: int64
      record:
        type: array
        items:
          type: string
          example: Necessitatibus dignissimos deleniti cum eaque qui non.
        example:
          - Magnam illum.
          - Cum sint beatae commodi omnis.
          - Voluptatum deserunt eius sapiente.
        minItems: 4
        maxItems: 4
    example:
      line_number: 7088058467520500921
      record:
        - Dolores nam.
        - Similique ipsam a.
        - Sit autem mollitia molestias asperiores.
    required:
      - record
      - line_number
  ProxyRecordRequestBody:
    title: ProxyRecordRequestBody
    type: object
    properties:
      line_number:
        type: integer
        description: номер строки в исходном файле
        example: 7354538568430021140
        format: int64
      record:
        type: array
        items:
          type: string
          example: Ut odio.
        example:
          - Doloremque architecto perferendis voluptas.
          - Sapiente dolor.
          - Vel exercitationem facilis recusandae voluptatem corrupti saepe.
        minItems: 4
        maxItems: 4
    example:
      line_number: 1009684138831546335
      record:
        - Fuga est.
        - Temporibus officia.
        - Magnam voluptatem nesciunt quaerat quasi incidunt sed.
    required:
      - record
      - line_number
  TargetUserRecordRequestBody:
    title: TargetUserRecordRequestBody
    type: object
    properties:
      line_number:
        type: integer
        description: номер строки в исходном файле
        example: 4794403152647380107
        format: int64
      record:
        type: array
        items:
          type: string
          example: Expedita non et.
        example:
          - Autem hic quia.
          - Labore quaerat.
        minItems: 2
        maxItems: 2
    example:
      line_number: 6420859373392840132
      record:
        - Et sit adipisci sed delectus est.
        - Corporis molestiae praesentium odio dolorum.
    required:
      - record
      - line_number
  TaskFileNamesRequestBody:
    title: TaskFileNamesRequestBody
    type: object
    properties:
      bots_filename:
        type: string
        description: название файла, из которого брали ботов
        example: Et modi vel ratione repellat dolores ab.
      proxies_filename:
        type: string
        description: название файла, из которого брали прокси
        example: Exercitationem suscipit sit nisi earum perspiciatis nobis.
      targets_filename:
        type: string
        description: название файла, из которого брали целевых пользователей
        example: Consequatur ea atque reprehenderit esse molestiae.
    example:
      bots_filename: Est dolore perferendis esse accusantium.
      proxies_filename: Maxime facilis aut.
      targets_filename: Animi aliquid aliquid.
    required:
      - bots_filename
      - proxies_filename
      - targets_filename
  TasksServiceCreateTaskDraftRequestBody:
    title: TasksServiceCreateTaskDraftRequestBody
    type: object
    properties:
      post_image:
        type: string
        description: фотография для постов
        example: Necessitatibus qui ducimus.
      text_template:
        type: string
        description: шаблон для подписи под постом
        example: Et consequatur corporis quis et.
      title:
        type: string
        description: название задачи
        example: Aliquam ea.
    example:
      post_image: Voluptatem voluptas architecto blanditiis.
      text_template: Ea facere ab dolorem ut.
      title: Aut iste voluptatem maiores praesentium.
    required:
      - title
      - text_template
      - post_image
  TasksServiceGetTaskNotFoundResponseBody:
    title: TasksServiceGetTaskNotFoundResponseBody
    type: object
    properties:
      bots_filename:
        type: string
        description: название файла, из которого брали ботов
        example: Molestiae alias ipsa.
      bots_num:
        type: integer
        description: количество ботов в задаче
        example: 2525427640572649452
        format: int64
      id:
        type: string
        example: 7D80331A-7620-D09D-7CCB-2EF87B797732
        format: uuid
      image:
        type: string
        description: base64 строка картинки
        example: Veniam et amet saepe.
      proxies_filename:
        type: string
        description: название файла, из которого брали прокси
        example: Ea ipsum perspiciatis.
      proxies_num:
        type: integer
        description: количество прокси в задаче
        example: 1544303140115761818
        format: int64
      status:
        type: integer
        example: 1197743406563025942
        format: int64
      targets_filename:
        type: string
        description: название файла, из которого брали целевых пользователей
        example: Omnis enim exercitationem saepe autem.
      targets_num:
        type: integer
        description: количество целевых пользователей в задаче
        example: 7482866392658868470
        format: int64
      text_template:
        type: string
        description: описание под постом
        example: Ut eligendi consequuntur nulla quasi ea.
      title:
        type: string
        description: название задачи
        example: Incidunt optio consequatur et est.
    example:
      bots_filename: Nihil expedita consequatur.
      bots_num: 4048283407980412804
      id: 76FB876C-96AC-91E7-BD21-B0C2988DDF65
      image: Aut nihil iste qui.
      proxies_filename: Fugit quibusdam expedita et.
      proxies_num: 4347010341549590437
      status: 5728205418193779270
      targets_filename: Dolor doloremque.
      targets_num: 5009067573545138336
      text_template: Consequatur ad architecto aliquid reprehenderit quas.
      title: Magni beatae.
    required:
      - id
      - text_template
      - image
      - status
      - title
      - bots_num
      - proxies_num
      - targets_num
  TasksServiceGetTaskOKResponseBody:
    title: TasksServiceGetTaskOKResponseBody
    type: object
    properties:
      bots_filename:
        type: string
        description: название файла, из которого брали ботов
        example: Quas cumque quo non id.
      bots_num:
        type: integer
        description: количество ботов в задаче
        example: 7519638950690887329
        format: int64
      id:
        type: string
        example: 5E3B665E-1239-9C12-9643-FFC1E6C04697
        format: uuid
      image:
        type: string
        description: base64 строка картинки
        example: Ea possimus exercitationem voluptate.
      proxies_filename:
        type: string
        description: название файла, из которого брали прокси
        example: Sunt voluptatem est eos ipsa eos similique.
      proxies_num:
        type: integer
        description: количество прокси в задаче
        example: 4312849141357382634
        format: int64
      status:
        type: integer
        example: 1038771339596380439
        format: int64
      targets_filename:
        type: string
        description: название файла, из которого брали целевых пользователей
        example: Ut asperiores aut debitis quo perferendis.
      targets_num:
        type: integer
        description: количество целевых пользователей в задаче
        example: 8430216521975790348
        format: int64
      text_template:
        type: string
        description: описание под постом
        example: Doloribus non exercitationem et.
      title:
        type: string
        description: название задачи
        example: Sapiente dolores ut error.
    example:
      bots_filename: Doloribus qui.
      bots_num: 8583824491962129692
      id: 1265498D-5A84-134A-1C7A-ED5B4B92788E
      image: Odio est deleniti nam qui.
      proxies_filename: Iusto facere ut et sed.
      proxies_num: 9150780881161936755
      status: 6866891862787740949
      targets_filename: Non aut velit delectus qui quidem sit.
      targets_num: 7457245773025350663
      text_template: Et ut aut.
      title: Dolores velit officiis iusto est.
    required:
      - id
      - text_template
      - image
      - status
      - title
      - bots_num
      - proxies_num
      - targets_num
  TasksServiceGetTaskUnauthorizedResponseBody:
    title: TasksServiceGetTaskUnauthorizedResponseBody
    type: object
    properties:
      bots_filename:
        type: string
        description: название файла, из которого брали ботов
        example: Eius ut placeat in et dolorem id.
      bots_num:
        type: integer
        description: количество ботов в задаче
        example: 6651546990893310746
        format: int64
      id:
        type: string
        example: A45D83CF-F038-77BB-220E-D79EFC31D198
        format: uuid
      image:
        type: string
        description: base64 строка картинки
        example: Voluptas voluptates suscipit aut rem.
      proxies_filename:
        type: string
        description: название файла, из которого брали прокси
        example: Est commodi.
      proxies_num:
        type: integer
        description: количество прокси в задаче
        example: 4122403796436682398
        format: int64
      status:
        type: integer
        example: 4675286422358908836
        format: int64
      targets_filename:
        type: string
        description: название файла, из которого брали целевых пользователей
        example: Rerum nihil explicabo ipsa autem est.
      targets_num:
        type: integer
        description: количество целевых пользователей в задаче
        example: 6910286739302548497
        format: int64
      text_template:
        type: string
        description: описание под постом
        example: Porro sed deleniti quaerat iusto enim.
      title:
        type: string
        description: название задачи
        example: Eum ullam porro dolorem numquam rerum eveniet.
    example:
      bots_filename: Atque dolorem est dignissimos magni tenetur.
      bots_num: 7021831119889669132
      id: 95545D09-3153-0F17-09F7-7FEB1545D780
      image: Accusantium ut deserunt amet enim aliquam.
      proxies_filename: Veritatis veniam tempore exercitationem aut.
      proxies_num: 8304552871006170733
      status: 495993541818847479
      targets_filename: Deserunt in quis in optio.
      targets_num: 1171031840493513408
      text_template: Rem cumque et tempora voluptates.
      title: Eius sunt et fuga.
    required:
      - id
      - text_template
      - image
      - status
      - title
      - bots_num
      - proxies_num
      - targets_num
  TasksServiceUploadFilesRequestBody:
    title: TasksServiceUploadFilesRequestBody
    type: object
    properties:
      bots:
        type: array
        items:
          $ref: '#/definitions/BotAccountRecordRequestBody'
        description: список ботов
        example:
          - line_number: 1530681320648418897
            record:
              - Et ex ab laudantium.
              - Quia accusamus laboriosam sit.
              - Id nisi.
          - line_number: 1530681320648418897
            record:
              - Et ex ab laudantium.
              - Quia accusamus laboriosam sit.
              - Id nisi.
      filenames:
        $ref: '#/definitions/TaskFileNamesRequestBody'
      proxies:
        type: array
        items:
          $ref: '#/definitions/ProxyRecordRequestBody'
        description: список проксей для использования
        example:
          - line_number: 5762439881369486609
            record:
              - Vero id nostrum dolor itaque molestiae.
              - Quae adipisci modi.
              - Dignissimos nam quis quaerat exercitationem ut inventore.
          - line_number: 5762439881369486609
            record:
              - Vero id nostrum dolor itaque molestiae.
              - Quae adipisci modi.
              - Dignissimos nam quis quaerat exercitationem ut inventore.
          - line_number: 5762439881369486609
            record:
              - Vero id nostrum dolor itaque molestiae.
              - Quae adipisci modi.
              - Dignissimos nam quis quaerat exercitationem ut inventore.
      targets:
        type: array
        items:
          $ref: '#/definitions/TargetUserRecordRequestBody'
        description: список аккаунтов, которым показать надо рекламу
        example:
          - line_number: 7457996689799145942
            record:
              - Sit mollitia voluptatibus aperiam ut necessitatibus et.
              - Fuga sit ipsam aliquam eveniet.
          - line_number: 7457996689799145942
            record:
              - Sit mollitia voluptatibus aperiam ut necessitatibus et.
              - Fuga sit ipsam aliquam eveniet.
          - line_number: 7457996689799145942
            record:
              - Sit mollitia voluptatibus aperiam ut necessitatibus et.
              - Fuga sit ipsam aliquam eveniet.
          - line_number: 7457996689799145942
            record:
              - Sit mollitia voluptatibus aperiam ut necessitatibus et.
              - Fuga sit ipsam aliquam eveniet.
    example:
      bots:
        - line_number: 1530681320648418897
          record:
            - Et ex ab laudantium.
            - Quia accusamus laboriosam sit.
            - Id nisi.
        - line_number: 1530681320648418897
          record:
            - Et ex ab laudantium.
            - Quia accusamus laboriosam sit.
            - Id nisi.
      filenames:
        bots_filename: Aliquid animi reiciendis magni.
        proxies_filename: Modi quo repellat nam quasi velit.
        targets_filename: Labore nihil.
      proxies:
        - line_number: 5762439881369486609
          record:
            - Vero id nostrum dolor itaque molestiae.
            - Quae adipisci modi.
            - Dignissimos nam quis quaerat exercitationem ut inventore.
        - line_number: 5762439881369486609
          record:
            - Vero id nostrum dolor itaque molestiae.
            - Quae adipisci modi.
            - Dignissimos nam quis quaerat exercitationem ut inventore.
      targets:
        - line_number: 7457996689799145942
          record:
            - Sit mollitia voluptatibus aperiam ut necessitatibus et.
            - Fuga sit ipsam aliquam eveniet.
        - line_number: 7457996689799145942
          record:
            - Sit mollitia voluptatibus aperiam ut necessitatibus et.
            - Fuga sit ipsam aliquam eveniet.
        - line_number: 7457996689799145942
          record:
            - Sit mollitia voluptatibus aperiam ut necessitatibus et.
            - Fuga sit ipsam aliquam eveniet.
    required:
      - bots
      - proxies
      - targets
      - filenames
  UploadErrorResponse:
    title: UploadErrorResponse
    type: object
    properties:
      input:
        type: string
        description: номер порта
        example: Distinctio tenetur et quidem et quasi soluta.
      line:
        type: integer
        example: 6128284373895418988
        format: int64
      reason:
        type: string
        example: Non beatae inventore itaque accusantium.
      type:
        type: integer
        description: |2-
           1 - список ботов
              2 - список прокси
              3 - список получателей рекламы
        example: 1
        enum:
          - 1
          - 2
          - 3
    example:
      input: Qui velit.
      line: 7645371658264885494
      reason: Voluptatem expedita itaque sint dolore consequatur animi.
      type: 1
    required:
      - type
      - line
      - input
      - reason
securityDefinitions:
  basic_header_Authorization:
    type: basic
    description: |-
      Basic authentication used to authenticate security principal during signin

      **Security Scopes**:
        * `driver`: Read-only access
  jwt_header_Authorization:
    type: apiKey
    description: |-
      Secures endpoint by requiring a valid JWT token retrieved via the signin endpoint. Supports scopes "api:read" and "api:write".

      **Security Scopes**:
        * `driver`: Read-only access
        * `admin`: Read and write access
    name: Authorization
    in: header
